In [14]:
import numpy as np
arr = np.arange(1,21)
print("Array : ",arr)

#Calculating the sum , mean , median and standard deviation of the array
print("Sum : ", np.sum(arr))
print("Mean : ", np.mean(arr))
print("Median : ", np.median(arr))
print("Standard Deviation : ", np.std(arr))

#Find indices of element which is greater tham 10
index10 = np.where(arr>10)
print(index10)



Array :  [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
Sum :  210
Mean :  10.5
Median :  10.5
Standard Deviation :  5.766281297335398
(array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19]),)


In [15]:
#create a 2D NumPy array of shape 4*4 with numbers 1 to 16
arr2D = np.arange(1,17)
arr2D = arr2D.reshape(4,4) 
print("2D Array : \n" , arr2D)

#Transpose
print("Transpose Array : \n", arr2D.T)

#row Wise and column wise sum
print("Row wise sum : " , np.sum(arr2D , axis=1))
print("Column wise sum : " , np.sum(arr2D , axis=0))

2D Array : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
Transpose Array : 
 [[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]
Row wise sum :  [10 26 42 58]
Column wise sum :  [28 32 36 40]


In [16]:
#create two 3x3 arrays with random integers (1 to 20)
arr1 = np.random.randint(1, 21, (3, 3))
arr2 = np.random.randint(1, 21, (3, 3))

print("Array A:\n", arr1)
print()
print("Array B:\n", arr2)
print()

print("Addition:\n", arr1 + arr2)
print()
print("Subtraction:\n", arr1 - arr2)
print()
print("Multiplication:\n", arr1 * arr2)


#dot product
print("Dot Product:\n", np.dot(arr1, arr2))


# reshape a 1D array of size 12 to 3*4 
arr_reshape = np.arange(1,13)
arr_reshape = arr_reshape.reshape(3,4)
print("Reshaped Array:\n", arr_reshape)
print()

# Slice first 2 rows and last 2 columns
print("Sliced (first 2 rows, last 2 columns):\n", arr_reshape[:2, -2:])

Array A:
 [[18 12  9]
 [ 8  4  9]
 [ 4  3 19]]

Array B:
 [[10 12 15]
 [ 1 10  4]
 [12 11  9]]

Addition:
 [[28 24 24]
 [ 9 14 13]
 [16 14 28]]

Subtraction:
 [[ 8  0 -6]
 [ 7 -6  5]
 [-8 -8 10]]

Multiplication:
 [[180 144 135]
 [  8  40  36]
 [ 48  33 171]]
Dot Product:
 [[300 435 399]
 [192 235 217]
 [271 287 243]]
Reshaped Array:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Sliced (first 2 rows, last 2 columns):
 [[3 4]
 [7 8]]
